title: Ada Pub
description: A site dedicated to resources in the Cardano ecosystem.
baseurl: "/ada-pub"
url: "https://nathanjessen.com"
permalink: pretty

theme: null
remote_theme: pmarsceill/just-the-docs

color_scheme: ada

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/nathanjessen/ada-pub"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
nav_sort: case_insensitive

# Footer "Edit this page on GitHub" link text
gh_edit_link: false
gh_edit_repository: "https://github.com/nathanjessen/ada-pub"
gh_edit_branch: "main"
gh_edit_link_text: "Edit this page on GitHub."
# gh_edit_source: docs
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Google Analytics Tracking
# ga_tracking: UA-5555555-55
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
