[build]
  command = "jekyll build"
  publish = "_site"

[[plugins]]
package = "netlify-plugin-checklinks"
  # Report on all broken links to external pages.
  # Enabling this will make your tests more brittle, since you can't control
  # external pages.
  checkExternal = true
